# 端口
server.port=8080

# MariaDB 远程数据库
spring.datasource.url=jdbc:mariadb://120.24.74.222:3306/contactdb
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=app
spring.datasource.password=app123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# 禁用静态资源缓存，确保浏览器总是加载最新页面
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
